# Generated by Django 6.0.5 on 2026-05-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(db_column='ID_Equipamento', primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(db_column='Numero_Serie', max_length=100, unique=True)),
                ('nome_equipamento', models.CharField(db_column='Nome_Equipamento', max_length=100)),
                ('status_operacional', models.CharField(db_column='Status_Operacional', max_length=30)),
                ('data_ultima_manutencao', models.DateField(blank=True, db_column='Data_Ultima_Manutencao', null=True)),
            ],
            options={
                'db_table': 'equipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.AutoField(db_column='ID_Exame', primary_key=True, serialize=False)),
                ('data_hora_solicitacao', models.DateTimeField(db_column='Data_Hora_Solicitacao')),
                ('regiao_corpo', models.CharField(db_column='Regiao_Corpo', max_length=100)),
                ('observacoes_clinicas', models.TextField(blank=True, db_column='Observacoes_Clinicas', null=True)),
            ],
            options={
                'db_table': 'exame',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExameStatus',
            fields=[
                ('id_exame_status', models.AutoField(db_column='ID_Exame_Status', primary_key=True, serialize=False)),
                ('data_modificacao', models.DateTimeField()),
            ],
            options={
                'db_table': 'exame_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagemMedica',
            fields=[
                ('id_imagem', models.AutoField(db_column='ID_Imagem', primary_key=True, serialize=False)),
                ('resolucao_largura', models.IntegerField(db_column='Resolucao_Largura')),
                ('data_hora_aquisicao', models.DateTimeField(db_column='Data_Hora_Aquisicao')),
                ('formato_arquivo', models.CharField(db_column='Formato_Arquivo', max_length=10)),
                ('tamanho_arquivo_mb', models.DecimalField(db_column='Tamanho_Arquivo_MB', decimal_places=2, max_digits=6)),
                ('caminho_armazenamento', models.CharField(db_column='Caminho_Armazenamento', max_length=255)),
                ('resolucao_altura', models.IntegerField(db_column='Resolucao_Altura')),
            ],
            options={
                'db_table': 'imagem_medica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inferencia',
            fields=[
                ('id_inferencia', models.AutoField(db_column='ID_Inferencia', primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField(db_column='Data_Hora_Inicio')),
                ('tempo_processamento', models.IntegerField(db_column='Tempo_Processamento')),
                ('status_resultado', models.CharField(db_column='Status_Resultado', max_length=30)),
            ],
            options={
                'db_table': 'inferencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id_laudo', models.AutoField(db_column='ID_Laudo', primary_key=True, serialize=False)),
                ('conteudo_final', models.TextField(blank=True, db_column='Conteudo_Final', null=True)),
                ('data_hora_assinatura', models.DateTimeField(blank=True, db_column='Data_Hora_Assinatura', null=True)),
                ('status_aprovacao', models.CharField(blank=True, db_column='Status_Aprovacao', max_length=30, null=True)),
                ('data_hora_geracao', models.DateTimeField(db_column='Data_Hora_Geracao')),
                ('texto_gerado', models.TextField(db_column='Texto_Gerado')),
                ('tokens_consumidos', models.IntegerField(db_column='Tokens_Consumidos')),
                ('prompt_utilizado', models.TextField(db_column='Prompt_Utilizado')),
            ],
            options={
                'db_table': 'laudo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(db_column='ID_Medico', primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(db_column='Nome_Completo', max_length=150)),
                ('crm', models.CharField(db_column='CRM', max_length=20, unique=True)),
                ('uf_crm', models.CharField(db_column='UF_CRM', max_length=2)),
                ('especialidade', models.CharField(db_column='Especialidade', max_length=100)),
                ('email_institucional', models.CharField(blank=True, db_column='Email_Institucional', max_length=150, null=True)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloMllm',
            fields=[
                ('id_modelo', models.AutoField(db_column='ID_Modelo', primary_key=True, serialize=False)),
                ('nome_modelo', models.CharField(db_column='Nome_Modelo', max_length=100)),
                ('versao', models.CharField(db_column='Versao', max_length=50)),
                ('arquitetura', models.CharField(db_column='Arquitetura', max_length=100)),
            ],
            options={
                'db_table': 'modelo_mllm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(db_column='ID_Paciente', primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(db_column='Nome_Completo', max_length=150)),
                ('cpf', models.CharField(db_column='CPF', max_length=11, unique=True)),
                ('data_nascimento', models.DateField(db_column='Data_Nascimento')),
                ('sexo', models.CharField(db_column='Sexo', max_length=15)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevisaoLaudo',
            fields=[
                ('id_revisao', models.AutoField(db_column='ID_Revisao', primary_key=True, serialize=False)),
                ('data_hora_revisao', models.DateTimeField(db_column='Data_Hora_Revisao')),
                ('concordancia', models.CharField(db_column='Concordancia', max_length=20)),
                ('observacao_tecnica', models.TextField(blank=True, db_column='Observacao_Tecnica', null=True)),
            ],
            options={
                'db_table': 'revisao_laudo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(db_column='ID_Status', primary_key=True, serialize=False)),
                ('descricao_status', models.CharField(db_column='Descricao_Status', max_length=50)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
    ]
